#!/bin/bash

message=$(sed -n '1p' $1)

if [[ ! $message =~ \#[0-9]{1,6}.* ]]; then
  echo '[POLICY] Commit message is not formatted correctly.';
  echo 'It should start with a # following the issue number, like:';
  echo '#12345 Commit message here';
  echo '';
  exit 1;
fi
